// Builds the root README.md (stats dashboard + problem index) from the central
// index kept at .grindlog/index.json in the output repo.
//
// index shape:
// {
//   problems: {
//     "3121-count-the-number-of-special-characters-ii": {
//       frontendId, title, slug, difficulty, topics: [],
//       solutions: [{ file, lang, runtime, runtimeMs, memory, runtimeBeats,
//                     memoryBeats, hash, submittedAt, dailyDate, failedAttempts }]
//     }, ...
//   }
// }

import { formatDate } from './format.js';

function runtimeMs(runtime) {
  if (!runtime) return null;
  const m = String(runtime).match(/([\d.]+)\s*ms/);
  return m ? parseFloat(m[1]) : null;
}

function bestRuntime(solutions) {
  let best = null;
  for (const s of solutions) {
    const ms = runtimeMs(s.runtime);
    if (ms != null && (best == null || ms < best)) best = ms;
  }
  return best != null ? `${best} ms` : '—';
}

// Consecutive-day streak over the set of daily-challenge dates, ending today or yesterday.
export function computeDailyStreak(dates, today = new Date()) {
  const set = new Set(dates);
  const day = new Date(today.getFullYear(), today.getMonth(), today.getDate());
  const iso = (d) => formatDate(d.getTime());
  // Streak may end today (already solved) or yesterday (today's not done yet).
  if (!set.has(iso(day))) day.setDate(day.getDate() - 1);
  let streak = 0;
  while (set.has(iso(day))) {
    streak += 1;
    day.setDate(day.getDate() - 1);
  }
  return streak;
}

export function buildRootReadme(index) {
  const problems = Object.entries(index.problems || {})
    .map(([key, p]) => ({ key, ...p }))
    .sort((a, b) => Number(a.frontendId) - Number(b.frontendId));

  const byDifficulty = { Easy: 0, Medium: 0, Hard: 0 };
  const byTopic = new Map();
  const dailyDates = [];
  let totalFailedAttempts = 0;
  let attemptsSamples = 0;

  for (const p of problems) {
    if (byDifficulty[p.difficulty] != null) byDifficulty[p.difficulty] += 1;
    for (const t of p.topics || []) {
      if (!byTopic.has(t)) byTopic.set(t, []);
      byTopic.get(t).push(p);
    }
    for (const s of p.solutions || []) {
      if (s.dailyDate) dailyDates.push(s.dailyDate);
      if (s.failedAttempts != null) {
        totalFailedAttempts += s.failedAttempts;
        attemptsSamples += 1;
      }
    }
  }

  const streak = computeDailyStreak(dailyDates);
  const avgAttempts = attemptsSamples ? (totalFailedAttempts / attemptsSamples + 1).toFixed(1) : null;

  const out = [];
  out.push('# LeetCode Solutions');
  out.push('');
  out.push('Auto-generated by **Grindlog**. Every accepted submission is kept — multiple approaches per problem.');
  out.push('');
  out.push('## Stats');
  out.push('');
  out.push(`- **Solved:** ${problems.length} (Easy: ${byDifficulty.Easy} · Medium: ${byDifficulty.Medium} · Hard: ${byDifficulty.Hard})`);
  if (streak > 0) out.push(`- **Daily Challenge streak:** ${streak} day${streak === 1 ? '' : 's'} 🔥`);
  if (avgAttempts) out.push(`- **Average submissions to accept:** ${avgAttempts}`);
  out.push('');
  out.push('## Problems');
  out.push('');
  out.push('| # | Problem | Difficulty | Topics | Approaches | Best runtime |');
  out.push('|---|---------|------------|--------|------------|--------------|');
  for (const p of problems) {
    const topics = (p.topics || []).join(', ');
    out.push(
      `| ${p.frontendId} | [${p.title}](./${encodeURIComponent(p.key)}) | ${p.difficulty} | ${topics} | ${(p.solutions || []).length} | ${bestRuntime(p.solutions || [])} |`
    );
  }
  out.push('');
  out.push('## By Topic');
  out.push('');
  const topics = Array.from(byTopic.keys()).sort();
  for (const t of topics) {
    const ps = byTopic.get(t);
    out.push(`<details><summary><strong>${t}</strong> (${ps.length})</summary>`);
    out.push('');
    for (const p of ps) {
      out.push(`- [${p.frontendId}. ${p.title}](./${encodeURIComponent(p.key)}) — ${p.difficulty}`);
    }
    out.push('');
    out.push('</details>');
  }
  out.push('');
  return out.join('\n');
}
